### ISSUE TITLE
Improvement suggestion:  display the timer in the title of the HTML document

### ISSUE THREAD

**Issue by joelsouza** [agustinl/daily.place#15]
Currently, the pomodoro timer is displayed within the web app, and users need to switch tabs to view the remaining time. I believe it would be useful if the timer could also be displayed in the title of the HTML document of the web app, so that users can see the remaining time by just looking at the browser tab.

As a web developer myself, I would like to offer to implement this change if it is deemed appropriate.

**Comment by agustinl** [comment]
Hi @joelsouza 

It is a good improvement. Please feel free to create a PR with the code 🚀

**Comment by agustinl** [comment]
Its live now,
Thanks
