### ISSUE TITLE
[enhancement] Remove fade out on sound repeat

### ISSUE THREAD

**Issue by wiiha** [agustinl/daily.place#5]
_First off, really like this project. I've been using it since I found it on HN. 👍_ 

**enhancement**
Whenever the sound reaches it's end, there is a fade out before it replays.
This fade out becomes very repetitive since the sound tracks aren't that long.
Would it be possible to remove the fade out so that it is perceived as long continues track?

BR,
Wilhelm

**Comment by agustinl** [comment]
Hi @wiiha , thanks for your feedback. I push some updates recently and now the sounds come from youtube videos, and can be played one at a time. This makes them longer, less repetitive and can be listened to for hours.

I think that solves the problem presented. As always, open to any feedback!

Have a nice week!

**Comment by wiiha** [comment]
Thanks, new update works great!
