### ISSUE TITLE
It's not possible to mix soundtracks anymore

### ISSUE THREAD

**Issue by pusewicz** [agustinl/daily.place#7]
Not sure if this was brought by the newest update, but before I was able to mix the soundtracks, eg. adding rain and fireplace to lofi.

Can't do that anymore.

**Comment by agustinl** [comment]
Hi @pusewicz 

Thats was a change in the last updated for two reasons:

1- The size of the audios used 100% of the bandwidth of the free CDN plan.

2- The audios had a limited duration of some minutes (1 in some cases). (More minutes more size -back to point 1-). This created an abrupt stop and play effect in loop. And it was more annoying than relaxing.

So, I chose to put youtube videos in background for sounds. That's reduce the kb size of transfer (0 from CDN), and I can select videos with hours of duration to reproduce without stopping.

I think it's possible to reproduce more than one YT video in the background, but I will investigate for a next update (including volume control).

Thanks for your concern and taking the time to write this issue!
I hope the app is useful for you anyway.  🙌

**Comment by agustinl** [comment]
Hi @pusewicz !
Support to mix soundtracks and volume control for each one will be released in next version this week 🚀
